# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0068_hide_scoreboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='problem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution', to='judge.Problem', verbose_name='associated problem'),
        ),
    ]
